Атмания. Task №4
Hisoka742/spbu_python_course pull request #7
Opened 2024-10-24 19:39 UTC by Hisoka742

# Summary
This pull request introduces an implementation of a thread pool pattern using Python’s ```threading``` module. The thread pool manages a fixed number of worker threads that execute tasks from a queue. Each task is a function that performs some computation and returns a result. The pull request also includes a comprehensive test suite using ```pytest``` to validate the correct behavior of the thread pool under different conditions.

# Key Features
**1. Thread Pool Class (```ThreadPool```):**

- Initializes with a fixed number of worker threads.
- Threads wait for tasks from a queue and execute them.
- The ```enqueue(task)``` method adds tasks to the queue for execution.
- The ```dispose()``` method gracefully shuts down the thread pool, ensuring that no new tasks are accepted after shutdown.
**2. Task Management:**

- Each task is a callable function that is added to the queue.
- Worker threads pick up tasks from the queue and execute them.
- Tasks are tracked using an event object to signal completion.
**Graceful Shutdown:**

- The ```dispose()``` method signals all threads to stop processing new tasks and waits for them to finish the ongoing tasks.
# Test Cases:
The following test cases are implemented to ensure the correctness of the thread pool:

1. ```test_basic_threadpool_execution```:

- Verifies that tasks are enqueued, executed by worker threads, and completed successfully.
- Uses a pool of 3 threads and enqueues 5 tasks to ensure thread reuse and task completion.
2. ```test_threadpool_size```:

- Checks that the thread pool initializes with the correct number of worker threads.
- Ensures that a pool created with ```n``` threads has exactly ```n``` threads running.
3. ```test_task_execution_and_reuse```:

- Ensures tasks are executed correctly by calculating the square of a number.
- Verifies that threads can handle multiple tasks by enqueuing more tasks than the number of threads.
4. ```test_dispose_stops_new_tasks```:

Verifies that after calling ```dispose()```, no new tasks can be added to the thread pool.
Ensures that ```enqueue()``` returns ```None``` when the thread pool is shut down

2024-10-25 08:49 UTC, Krekep requested changes
Необходимы исправления

2024-10-25 08:49 UTC, Krekep commented on project/ThreadPool/main.py
> +from queue import Queue
Класс `Queue` реализует в себе методы для синхронизации потоков. По условию задачи использовать пакеты помимо `threading` для работы с потоками запрещено.

2024-10-25 08:49 UTC, Krekep commented on tests/test_threadPool.py
> +    assert len(pool.threads) == 4  # Ensure 4 threads were created
Этот тест проверяет, что Вы добавили в массив `threads` 4 элемента. Он не проверяет, что в данный момент времени в системе запущено 4 активных и работающих потока. Попробуйте использовать `threading.active_count()`

2024-10-25 14:34 UTC, Hisoka742 commented on project/ThreadPool/main.py
> +from queue import Queue
Теперь всё работает корректно. Спасибо за ваши комментарии!

2024-10-25 14:34 UTC, Hisoka742 commented on tests/test_threadPool.py
> +    assert len(pool.threads) == 4  # Ensure 4 threads were created
Теперь всё работает корректно. Спасибо за ваши комментарии!

2024-11-02 08:12 UTC, Krekep approved these changes
Зачтено, но не забывайте запрашивать review

2024-11-02 08:12 UTC, Krekep commented on project/ThreadPool/main.py
Файл лучше переименовать, т.к. имя `main.py` не несёт в себе смысловой нагрузки

2024-11-02 08:12 UTC, Krekep commented on project/ThreadPool/main.py
> +    def worker(self):
Не хватает `docstring` у всех функций

2024-11-15 09:16 UTC, Krekep approved these changes
После того, как задача зачтена не нужно запрашивать ревью. Ревью нужно запрашивать, когда Вы готовы показать сделанное задание на оценку мне. После того, как задача зачтена, надо слить изменения из ветки задания с веткой master

2024-11-16 01:29 UTC, merged