Атмания. Task №7
Hisoka742/spbu_python_course pull request #9
Opened 2024-11-05 17:39 UTC by Hisoka742

## Overview

1. **Data Loading and Preprocessing (```main.py```):** Contains functions for loading, preprocessing, and analyzing the Titanic dataset.
2. **Visualization (```Visualization.py```):** Generates a variety of visualizations for data exploration, including interactive, 3D, and specialized plots.
3. **Testing (```test.py```):** Unit tests for core functions using sample data, ensuring correctness in data processing and analysis.

## Files and Functions
### ```main.py``` - Titanic Data Loading and Preprocessing
- Functions:
1. **```load_and_concat_data```:** Loads Titanic train and test datasets and combines them, adding a column to distinguish between train/test data.
2. **```preprocess_data```:** Cleans and preprocesses the data, handling missing values, converting categorical fields, engineering features like ```FamilySize``` and ```CabinBool```, and extracting titles from names.
3. **```get_class_counts```:** Returns counts of passengers by class.
4. **```get_age_by_class_and_gender```:** Calculates average age by passenger class and gender, identifying the youngest and oldest groups and computing age differences.
5. **```filter_k_survivors```:** Filters survivors whose last names start with "K" and returns them sorted by fare.
6. **```max_relatives_with_survivor```:** Finds the maximum number of relatives for any survivor.
7. **```compare_fare_by_cabin```:** Compares the average fare of passengers with and without cabin information.

### ```Visualization.py``` - Data Visualization
- **Objective:** Provides an exploratory data analysis through a set of 10 unique charts on the Titanic data. This includes various plot types, with 5 .interactive plots, one 3D plot, and specialized charts:
- Scatter, line, histogram, bar (vertical and horizontal), pie, box, sunburst, and a bonus Sankey diagram (for +2 points) in Plotly.
- **Libraries:** Utilizes Seaborn, Plotly, and Matplotlib for diverse and interactive data visualization.

### ```test.py``` - Unit Tests for Data Processing Functions
- **Setup:** Uses ```pytest``` with a sample dataset fixture (```sample_data```) to verify each function's accuracy.

- **Tests:**
1. ```test_class_counts:``` Verifies passenger count by class.
2. ```test_age_by_class_and_gender:``` Confirms the correct age statistics (youngest, oldest, and age difference) by class and gender.
3. ```test_filter_k_survivors:``` Checks that survivors with last names starting with "K" are correctly filtered and sorted by fare.
4. ```test_max_relatives_with_survivor:``` Ensures the function identifies the maximum number of relatives among survivors.
5. ```test_compare_fare_by_cabin:``` Validates that average fares are correctly calculated and compared between passengers with and without cabins.

2024-11-06 07:35 UTC, Krekep requested changes
Задание необходимо выполнить в `jupyter notebook`

2024-11-06 19:00 UTC, Hisoka742 commented
> Задание необходимо выполнить в `jupyter notebook`

В Jupyter Notebook все диаграммы работают, но когда я добавляю их в Github, некоторые из них не работают.

2024-11-07 17:10 UTC, Hisoka742 commented
**https://colab.research.google.com/drive/1kVql0DQF8zP3teAsYbwl6j6Ztv3DuW1-?usp=sharing** @Krekep

2024-11-09 09:56 UTC, Krekep requested changes
Очень хорошо, но надо поправить небольшие замечания в notebook. Комментарии написаны в Google colab, если их не видно, могу продублировать сюда, но напишите об этом

2024-11-09 19:56 UTC, Hisoka742 commented
> Очень хорошо, но надо поправить небольшие замечания в notebook. Комментарии написаны в Google colab, если их не видно, могу продублировать сюда, но напишите об этом

Я исправил

2024-11-11 13:34 UTC, Krekep requested changes
Вы не добавили вывод данных после их конкатенации, хотя это было в комментариях предыдущего ревью. На текущий момент не могу зачесть, вывод данных всё-таки надо добавить (учтите, что надо вывести как начало датасета, так и конец)

2024-11-15 11:14 UTC, Krekep approved these changes
Зачтено, но ревью запрошено после дедлайна, так что половина баллов

2024-11-16 01:29 UTC, merged